# Generated by Django 3.1.7 on 2021-04-09 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='grades',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='classes',
            new_name='clase',
        ),
    ]
