# Generated by Django 3.1.7 on 2021-06-24 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20210409_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='score',
            name='description',
        ),
        migrations.RemoveField(
            model_name='score',
            name='name',
        ),
        migrations.RemoveField(
            model_name='score',
            name='unit',
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.class')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.grade')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.unit')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.work'),
        ),
    ]
